from collections.abc import Callable
from typing import Any, Protocol, TypeVar, overload

_F = TypeVar("_F", bound=Callable[..., object])

class _Task(Protocol):
    def __call__(self, *args: object, **kwargs: object) -> Any: ...
    def expand(self, **kwargs: object) -> Any: ...

def dag(**kwargs: object) -> Callable[[_F], _F]: ...
@overload
def task(func: Callable[..., object], /) -> _Task: ...
@overload
def task(*, retries: int = ...) -> Callable[[Callable[..., object]], _Task]: ...
def get_current_context() -> dict[str, Any]: ...

class Variable:
    @classmethod
    def get(cls, key: str, default: object = ...) -> object: ...
    @classmethod
    def set(cls, key: str, value: str) -> None: ...
